version: "3"
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"

volumes:
  sqlvolume: